#!/usr/bin/env python
#
#    Copyright 2016 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

import argparse
import logging
import os


def filename(string):
    if not os.path.exists(string):
        msg = "Path %r is not exists" % string
        raise argparse.ArgumentTypeError(msg)
    if not os.path.isfile(string):
        msg = "File %r is not a file" % string
        raise argparse.ArgumentTypeError(msg)
    return string


def main():
    # TODO: Update configuration parameters from environment variables
    # defaults = {
    #     'CONFIG_FILE': 'config.yaml',
    # }
    # defaults = {k: os.environ.get(k, v) for k, v in defaults.items()}

    parser = argparse.ArgumentParser(description='Report to testrail')

    parser.add_argument('--config', '-c',
                        type=filename,
                        default='',
                        help='Configuration file')
    parser.add_argument('--verbose', '-v',
                        action='store_true',
                        default=False,
                        help='Verbose mode')

    from treporter.settings import init_conf
    args = parser.parse_args()
    conf, logger = init_conf(args.config)
    if args.verbose:
        conf['common']['log_level'] = 'DEBUG'

    from treporter.reporter import Reporter
    reporter = Reporter(
        xunit_report=conf['test_results']['xunit']['filename'],
        iso_link='ISO_LINK',
        iso_id='ISO_ID',
        env_description='ENVIRONMENT_DESCRIPTION',
        test_results_link='JENKINS_JOB_LINK',
    )

    reporter.config_testrail(
        base_url=conf['testrail']['url'],
        username=conf['testrail']['username'],
        password=conf['testrail']['password'],
        milestone=conf['testrail']['milestone'],
        project=conf['testrail']['project'],
        tests_suite=conf['testrail']['test_suite'])
    reporter.execute()


if __name__ == '__main__':
    logging.root.addHandler(logging.StreamHandler())
    main()
