---
case:
 case-name: 3 Controller, 1 Compute, 2 Ceph, Ceph for images and volumes on Neutron/VLAN
 group-name: 3ctrl_1comp_2ceph_cephVol_cephImg_neutronVLAN
 slaves: 6

network-config: &network-config
 provider: neutron
 segment-type: vlan
 pubip-to-all: false

storages-config: &storages-config
 volume-lvm: false
 volume-ceph: true
 image-ceph: true
 ephemeral-ceph: false
 rados-ceph: false
 replica-ceph: 2

nodes-ifaces: &iface-config
    - eth0:
      - admin
      - public
      - managment
      - storage
      - private

nodes: &nodes
 - roles:
    - controller
   # iface: *iface-config
   count: 3
 - roles:
    - compute
   # iface: *iface-config
   count: 1
 - roles:
    - ceph-osd
   # iface: *iface-config
   count: 2


environment-config: &environment-config
 name: env1
 release: ubuntu
 components:
  sahara: falce
  murano: false
  ceilometer: false
 network: *network-config
 storages: *storages-config
 nodes: *nodes
