---

network-config: &network-config
 provider: neutron
 segment-type: vlan
 pubip-to-all: false

storages-config: &storages-config
 volume-lvm: true
 volume-ceph: false
 image-ceph: false
 ephemeral-ceph: false
 rados-ceph: false
 replica-ceph: 2

nodes-ifaces: &iface-config
    - eth0:
      - admin
      - public
      - managment
      - storage
      - private

nodes: &nodes
 - roles:
    - controller
   # iface: *iface-config
   count: 1
 - roles:
    - compute
   # iface: *iface-config
   count: 1
 - roles:
    - cinder
   # iface: *iface-config
   count: 1

template:
 name: 1 Controller, 1 Compute, 1 Cinder on Neutron/VLAN
 group-name: 1ctrl_1comp_1cinder_neutronVLAN
 slaves: 3
 cluster-template: &environment-config
  name: env1
  release: ubuntu
  settings:
   components:
    sahara: false
    murano: false
    ceilometer: false
   storages: *storages-config
  network: *network-config
  nodes: *nodes
